<?php
/** @var $this Zend_View */
$this->headLink(array('rel' => 'favicon', 'type' => 'image/x-icon', 'href' => '/favicon.ico'));

/* Title */
$this->headTitle('Skeleton');
$this->headTitle()->setSeparator(' / ');

?>
<?php echo $this->doctype() ?>
<html>
<head>
    <?php echo $this->headTitle(); ?>
    <?php echo $this->headMeta(); ?>
    <?php echo $this->headLink(); ?>
    <?php echo $this->headStyle(); ?>
    <?php echo $this->headScript(); ?>
</head>
<body>
    <?php echo $this->layout()->content; ?>
</body>
</html>
